[platformio]
boards_dir = boards
default_envs = mu_f042_swd_probe

[env]
platform = ststm32
board = mu_f042f6p6
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
lib_archive = no
lib_ldf_mode = deep+
build_flags =
  -std=gnu++17
  -DSTM32F042x6
  -DSTM32F0
  -DSTM
  -DF0
  -DMU_BOARD
  -Iinclude
  -Ilib/comheadan/include
  -Ilib/braiteoiri/include
  -Wl,--print-memory-usage
board_build.ldscript = STM32F042F6PX_FLASH.ld

[env:mu_f042_swd_probe]
build_src_filter =
  +<mu_swd_probe.cpp>

[env:mu_f042_bare_can]
build_flags =
  ${env.build_flags}
  -DCAN_COMPATIBLE
build_src_filter =
  +<mu_bare_can.cpp>

[env:mu_f042_spi_probe]
build_src_filter =
  +<mu_spi_probe.cpp>

[env:mu_f042_adc_probe]
build_src_filter =
  +<mu_adc_probe.cpp>

[env:mu_f042_pulse_capture]
build_src_filter =
  +<mu_pulse_capture.cpp>

[env:mu_f042_flight_logger]
build_src_filter =
  +<mu_flight_logger.cpp>

[env:mu_f042_flight_logger_erase]
build_flags =
  ${env.build_flags}
  -DMU_ERASE_FLASH_ON_BOOT=1
build_src_filter =
  +<mu_flight_logger.cpp>
